import localFont from "next/font/local";
import "./globals.css";
import { Press_Start_2P, Fira_Code, Fira_Mono} from 'next/font/google'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pressPlay = Press_Start_2P({weight:"400", subsets: ['latin']})
const firaCode = Fira_Code({weight: ["300", "400", "500", "700"], subsets: ['latin']});
const firaMono = Fira_Mono({ weight: ["400", "500", "700"], subsets: ["latin"] });


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-full">
      <body className={`${firaCode.className} h-screen bg-background text-text`}>
        {children}
      </body>
    </html>
  );
}
