import localFont from "next/font/local";
import "./globals.css";
import { Press_Start_2P } from 'next/font/google'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pressPlay = Press_Start_2P({weight:"400", subsets: ['latin']})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-full">
      <body className={`${pressPlay.className} h-screen bg-background text-text`}>

        {children}
      </body>
    </html>
  );
}
